#pragma once
/**
 * @file  Input_Key_Binding.h
 *
 * @brief  Stores information about one key binding loaded from a configuration
 *         file.
 */

#include "JuceHeader.h"
#include "Locale_TextUser.h"
#include "Text_CharTypes.h"

namespace Input { namespace Key { class Binding; } }

class Input::Key::Binding : public Locale::TextUser
{
public:
    /**
     * @brief  Immutably sets all key binding information on construction.
     *
     * @param jsonKey         The action key string used to load key information
     *                        from keyBindings.json.
     *
     * @param keyDescription  A JUCE key description, suitable for constructing
     *                        a juce::KeyPress object.
     *
     * @param keyName         A name used to represent the bound key in the user
     *                        interface.
     *
     * @param charName        A single character used as an alternate way to
     *                        display the bound key.
     */
    Binding(const juce::Identifier& jsonKey,
            const juce::String keyDescription,
            const juce::String keyName,
            const Text::CharValue charName);

    /**
     * @brief  Constructs an invalid Binding with no stored data.
     */
    Binding();

    virtual ~Binding() { }

    /**
     * @brief  Gets the JUCE::KeyPress object for this binding's keyboard key.
     *
     * @return   A KeyPress object usable for checking if this key is held down.
     */
    juce::KeyPress getKeyPress() const;

    /**
     * @brief  Gets the identifier used to select this binding's assigned
     *         action.
     *
     * @return  The Identifier key that Input::Key::ConfigFile uses to represent
     *          the action assigned to this binding.
     */
    const juce::Identifier& getActionID() const;

    /**
     * @brief  Gets the localized description of this binding's action.
     *
     * @return  The localized action description, used when displaying key
     *          bindings to the user.
     */
    juce::String getActionDescription() const;

    /**
     * @brief  Gets the name used to describe the bound key to the user.
     *
     * @return  The bound key name, used when displaying key bindings to the
     *          user.
     */
    const juce::String& getKeyName() const;

    /**
     * @brief  Gets the character value used to represent this key binding.
     *
     * @return  A single character value, displayed using Text::Painter in order
     *          to represent this binding.
     */
    const Text::CharValue getCharName() const;

private:
    // The keyBindings.json identifier used to track this binding's action:
    const juce::Identifier& jsonKey;
    // JUCE key text, as generated by juce::KeyPres::getTextDescription():
    const juce::String keyDescription;
    // A name used to represent this key within the user interface:
    const juce::String keyName;
    // A single character value used to represent this key:
    const Text::CharValue charName;
};
