.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2017 Stephen Paul Weber <singpolyma@singpolyma.net>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH YOUR-APPLICATION 1 "May 14, 2019"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
Your-Application \- Replace with brief description.
.SH SYNOPSIS
.B Your-Application
.RI [ options ]
.SH DESCRIPTION
Replace this page with documentation for
.B your application.
.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
Avoid releasing projects without updating, replacing, or removing this file.
.SH OPTIONS
.TP
.B \-\-help
Show summary of options.
.TP
.B \-\-test
Run application tests, if built with testing enabled.
.TP
.B \-v
Print verbose output when running tests.
.TP
.B \-categories [category names]
Only run tests within the listed categories.
