########################### Layout Module ######################################
LAYOUT_DIR = Source/GUI/Layout
LAYOUT_COMPONENT_DIR := $(LAYOUT_DIR)/Component
LAYOUT_GROUP_DIR := $(LAYOUT_DIR)/Group
LAYOUT_TRANSITION_DIR := $(LAYOUT_DIR)/Transition

LAYOUT_PREFIX := Layout_
LAYOUT_OBJ := $(JUCE_OBJDIR)/$(LAYOUT_PREFIX)

LAYOUT_COMPONENT_PREFIX := $(LAYOUT_PREFIX)Component_
LAYOUT_COMPONENT_OBJ := $(LAYOUT_OBJ)Component_
OBJECTS_LAYOUT_COMPONENT := \
  $(LAYOUT_COMPONENT_OBJ)ConfigLayout.o \
  $(LAYOUT_COMPONENT_OBJ)JSONResource.o \
  $(LAYOUT_COMPONENT_OBJ)ConfigFile.o \
  $(LAYOUT_COMPONENT_OBJ)Manager.o

LAYOUT_GROUP_PREFIX := $(LAYOUT_PREFIX)Group_
LAYOUT_GROUP_OBJ := $(LAYOUT_OBJ)Group_
OBJECTS_LAYOUT_GROUP := \
  $(LAYOUT_GROUP_OBJ)RelativeLayout.o \
  $(LAYOUT_GROUP_OBJ)Manager.o

LAYOUT_TRANSITION_PREFIX := $(LAYOUT_PREFIX)Transition_
LAYOUT_TRANSITION_OBJ := $(LAYOUT_OBJ)Transition_
OBJECTS_LAYOUT_TRANSITION := \
  $(LAYOUT_TRANSITION_OBJ)Animator.o

OBJECTS_LAYOUT := \
  $(OBJECTS_LAYOUT_COMPONENT) \
  $(OBJECTS_LAYOUT_GROUP) \
  $(OBJECTS_LAYOUT_TRANSITION)

OBJECTS_LAYOUT_TEST :=

ifeq ($(BUILD_TESTS), 1)
    OBJECTS_LAYOUT := $(OBJECTS_LAYOUT) $(OBJECTS_LAYOUT_TEST)
endif

GUI_MODULES := $(GUI_MODULES) layout

OBJECTS_APP := $(OBJECTS_APP) $(OBJECTS_LAYOUT)

layout : $(OBJECTS_LAYOUT)
	@echo "    Built Layout module"

$(LAYOUT_COMPONENT_OBJ)ConfigLayout.o : \
    $(LAYOUT_COMPONENT_DIR)/$(LAYOUT_COMPONENT_PREFIX)ConfigLayout.cpp
$(LAYOUT_COMPONENT_OBJ)JSONResource.o : \
    $(LAYOUT_COMPONENT_DIR)/$(LAYOUT_COMPONENT_PREFIX)JSONResource.cpp
$(LAYOUT_COMPONENT_OBJ)ConfigFile.o : \
    $(LAYOUT_COMPONENT_DIR)/$(LAYOUT_COMPONENT_PREFIX)ConfigFile.cpp
$(LAYOUT_COMPONENT_OBJ)Manager.o : \
    $(LAYOUT_COMPONENT_DIR)/$(LAYOUT_COMPONENT_PREFIX)Manager.cpp

$(LAYOUT_GROUP_OBJ)RelativeLayout.o : \
    $(LAYOUT_GROUP_DIR)/$(LAYOUT_GROUP_PREFIX)RelativeLayout.cpp
$(LAYOUT_GROUP_OBJ)Manager.o : \
    $(LAYOUT_GROUP_DIR)/$(LAYOUT_GROUP_PREFIX)Manager.cpp

$(LAYOUT_TRANSITION_OBJ)Animator.o : \
    $(LAYOUT_TRANSITION_DIR)/$(LAYOUT_TRANSITION_PREFIX)Animator.cpp
